---
title: "Shiny app"
author: "Xiyu Hao"
date: "2022/12/1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(shiny)
library(shinythemes)
library(bslib)
library(shinydashboard)

Chinese <- read_csv("Chinese_restaurant_new.csv")
Korean <- read_csv("Korean_restaurant_new.csv")

```
# barplot
```{r}
barplot <- function(df) {
  ggplot(df, aes(x=stars)) +
  geom_histogram(fill="lightblue", aes(y = after_stat(count / sum(count))),binwidth=.25) +
  scale_y_continuous(labels = scales::percent) +
  labs( x = 'Stars', y = 'Percent of Total') +
  theme_minimal()
  
}
```

# app
```{r}
ui <- fluidPage(
  theme = shinytheme("flatly"),
  navbarPage("Restaurants",
  tabPanel("Ratings Plot",
  titlePanel("Restaurant Ratings"),
  sidebarLayout( 
    sidebarPanel(
      selectInput("dataset", "Choose a dataset:", 
                  choices = c("Chinese", "Korean")),
    selectInput("Delivery",
                "Restaurants Delivery",
                choices = unique(chinese$RestaurantsDelivery), 
                multiple = FALSE),
    selectInput(
				inputId = "Reservations",
				label = "Restaurants Reservations",
				choices = unique(chinese$RestaurantsReservations),
				selected = NULL,
				multiple = FALSE,
				selectize = FALSE
			)
    
    
    ),
  
  mainPanel(
      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = "tabs",
                  tabPanel("Plot", 
                           h4("Restaunrant Star Ratings"),
                           plotOutput("barplot")),
                  tabPanel("Summary", verbatimTextOutput("summary"))
      ) 
    )
    
  )
),
tabPanel("More",
    h4("For more information, please contect:"),
    "DUOHAN ZHANG (dzhang357@wisc.edu)", br(),
    "SHUWEI LIU (sliu777@wisc.edu)",br(),
    "XINYAN WANG (xwang2587@wisc.edu)",br(),
    "XIYU HAO (xhao33@wisc.edu)"
    )
))

server <- function(input, output) {
  # Return the requested dataset
  datasetInput <- reactive({
    switch(input$dataset,
           "Chinese" = Chinese,
           "Korean" = Korean)
  })
  current_data <- reactive({
    datasetInput() %>%
      filter(
        RestaurantsDelivery %in% input$Delivery,
        RestaurantsReservations %in% input$Reservations
      
      )
  })
  output$barplot <- renderPlot({
    barplot(current_data())}, height = 500, width = 700)
  # Generate a summary of the dataset
  output$summary <- renderPrint({
    dataset <- current_data()
    summary(dataset$stars)
  })
  
  
}

shinyApp(ui, server)
```

# Page

```{r}
ui <- fluidPage(
  theme = bs_theme(version = 4, bootswatch = "minty"),
  navbarPage("Restaurants",
  tabPanel("Plot",
  titlePanel("Restaurant Ratings"),
  sidebarLayout( 
    sidebarPanel(
    selectInput("Delivery",
                "Restaurants Delivery",
                choices = unique(chinese$RestaurantsDelivery), 
                multiple = FALSE),
    selectInput(
				inputId = "Reservations",
				label = "Restaurants Reservations",
				choices = unique(chinese$RestaurantsReservations),
				selected = NULL,
				multiple = FALSE,
				selectize = FALSE
			)
    ),
  
  mainPanel(
      plotOutput("barplot")  
    )
    
  )
  ),
  tabPanel("Summary",
    verbatimTextOutput("summary")
  ),
  tabPanel("More",
    h5("For more information, please contect:"),
    "DUOHAN ZHANG (dzhang357@wisc.edu)", br(),
    "SHUWEI LIU (sliu777@wisc.edu)",br(),
    "XINYAN WANG (xwang2587@wisc.edu)",br(),
    "XIYU HAO (xhao33@wisc.edu)"
    )
)
)


server <- function(input, output) {
  current_data <- reactive({
    chinese %>%
      filter(
        RestaurantsDelivery %in% input$Delivery,
        RestaurantsReservations %in% input$Reservations
      
      )
  })
  output$barplot <- renderPlot({
    barplot(current_data())
  })
 # Generate a summary of the dataset
  output$summary <- renderPrint({
    dataset <- current_data()
    summary(dataset$stars)
  })
  
}

shinyApp(ui, server)
```
